services:
  # Do not expose the database port, connect to it via the container instead.
  database:
    image: mysql # The database is launched from an online image.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
        # Here, we mount the db folder to place the script inside it in the entrypoint of this container.
        # This will cause the mysql container to execute this script and thus add our database.
      - ./db:/docker-entrypoint-initdb.d
    environment:
    # The value of this environment variable is set as the value of MYSQL_ROOT_PASSWORD.
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  server:
    image: db_server
    restart: always
    build:
      context: ./server
    ports:
      - ${SERVER_PORT}:5000
    depends_on:
      - database
    env_file:
      - secrets.env